### PR TITLE
Update

### PR DESCRIPTION
**Pull request by jburel**
Fix the various build errors

### CODE REVIEW

**Comment by will-moore** [comment]
Seems to be failing with:
```
+ OMERO_DIST=/opt/omero/server/OMERO.server
+ omero /omero-mkngff -h
```
Should be `omero mkngff -h` I think.

**Comment by jburel** [comment]
@will-moore @joshmoore I have removed the test in commit https://github.com/IDR/omero-mkngff/pull/18/commits/b0d11c1fab590305f0390497c92715a88a7b768d
this is coming from
https://github.com/German-BioImaging/omero-rdf/blob/main/test/integration/clitest/test_rdf.py
and it does not seem to make sense to have it in this repo

**Comment by will-moore** [comment]
Failing on tests with:

```
    def test_mkngff(self, capfd):  # type: ignore
        name = self.uuid()
        object_type = "Project"
        oid = self.create_object(object_type, name=f"{name}")
        obj_arg = f"{object_type}:{oid}"
        self.args += [obj_arg]
>       out = self.rdf(capfd)
E       AttributeError: 'TestMkngff' object has no attribute 'rdf'
```
I don't know if these have ever passed? Look like they come from the cookiecutter at https://github.com/ome/cookiecutter-omero-cli-plugin/blob/9b08be31192faf9c8f128efe0f7155bc57b2556b/omero-%7B%7Bcookiecutter.cli_command%7D%7D/test/integration/clitest/test_%7B%7Bcookiecutter.cli_command%7D%7D.py#L41

**Comment by will-moore** [comment]
Seems it needs at least 1 test to pass to be green.
Last run has:

```
============================== 1 warning in 0.31s ==============================
...
Error: Process completed with exit code 5.
```
Whereas the previous (green) has
```
========================= 1 passed, 1 warning in 0.56s =========================
```

**Review by will-moore — APPROVED** [review]
LGTM - build is green. Thanks 👍

**Pull request merged**
